### ISSUE TITLE
Error during native compilation

### ISSUE THREAD

**Issue by yantar92** [tecosaur/orgdiff#1]
I am getting the following error during native-compilation of the package:

    Warning (comp): /home/yantar92/.emacs.d/straight/build/orgdiff/orgdiff.el: Error: Symbol's value as variable is void orgdiff--set-file-1

**Comment by tecosaur** [comment]
Hmm, I wonder if this is similar to my (unresolved) issues in https://github.com/melpa/melpa/pull/7327 ?

**Comment by tecosaur** [comment]
Should be resolved as of fe4329c71ad9bf49efe9a561de426dde96e9b63b.
